[mqtt]
; MQTT broker configuration
; Hostname of mqtt broker (default=localhost)
; broker=localhost

; Port to connect to (default=1883)
; port=1883

; Use TLS (default=0)
; tls=0

; Username and password
; user=
; password=

; MQTT prefix to use (default=cec-mqtt)
; prefix=cec-mqtt

; Name of your device (default=CEC Bridge)
; name=cec-mqtt-bridge

[cec]
; HDMI-CEC configuration
; ID of CEC controller
; id=1

; Port where the CEC device is connected.
; Always prefer the value shown as "com port" in `cec-client -l`.
; compilation using the Linux Kernel driver (default=Linux):
; port=Linux
; compilation using the old Raspberry Pi driver:
; port=RPI
; some KMS setups may also work with:
; port=/dev/cec0
; port=/dev/cec1

; Devices to query (comma separated, defaults to all devices)
; devices=0,2,3,4,5

; Name of your device (default=CEC Bridge)
; name=CEC Bridge

; device power state refresh time in seconds (default=30) (min 10) (0 disables refresh)
; refresh=30

; CEC key press duration in milliseconds (default=0) (0 disables key release)
; keypress_duration_ms=0

; Minimum gap between key presses in milliseconds (default=200)
; keypress_gap_ms=200
